spring.application.name=liquibase-model-first
server.port=8083
spring.docker.compose.lifecycle-management=start_only
spring.datasource.url=jdbc:postgresql://localhost:35432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
#spring.liquibase.drop-first=true