spring.application.name=spring-liquibase-demo
spring.docker.compose.lifecycle-management=start_only

################ Database #####################
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
#spring.liquibase.drop-first=true